### ISSUE TITLE
IE11 rendering issues.

### ISSUE THREAD

**Issue by MattyBalaam** [bhovhannes/svg-url-loader#92] opened 2017-05-08 15:12 UTC
I'm unsure if you would consider this within the scope of the project, but felt it might be useful to report to help anyone else in future.

I have noticed that using this method of SVG for background-images, in my case, any image which is over the data threshold of 4026 and not served as an external image appear as pure black, when colours are defined in a <style> block.

This is a Windows 7 machine.

Switching back to using url-loader and the issue cannot be reproduced.
 
![image](https://cloud.githubusercontent.com/assets/1246923/25810064/dec7d3c6-3406-11e7-8ae9-5a0613fe3f7c.png)

I have attached a zip archive with an svg which is just over the failure threshold when viewed as a background-image

[ie11-fail.zip](https://github.com/bhovhannes/svg-url-loader/files/983920/ie11-fail.zip)

**Comment by simofacc** [comment] 2017-06-08 07:09
@MattyBalaam I had the same issue recently but it's not tied specifically to svg-url-loader as I was using the post-css loader to transform SVG files into base64 encoded strings. The issue is that the rendering engine of IE11 works differently for SVG images used as CSS background images, which causes the <style></style> block of SVG files to not work.

The only solution that worked for me was to re-export the SVG images with embedded inline styles using Adobe Illustrator.

Check out my steps here https://www.simonfacciol.com/blog/ie11-svg-background-images-not-displaying-correctly

**Comment by MattyBalaam** [comment] 2017-06-08 07:14
@simofacc This is true, you can use inline styles to get around the 4026 threshold, but style tags in SVGs will work under this size, I have been using this rule successfully on this site. https://www.neweraed.co.uk/

Generally I find this is a fairly happy medium threshold for my use case anyway to keep a filesize balance.

**Comment by MattyBalaam** [comment] 2017-06-08 07:19
@simofacc Just had a further thought that someone could write a loader or postcss plugin to rewrite style declarations into inline ones in SVGs. Perhaps someone already has.

**Comment by simofacc** [comment] 2017-06-08 07:20
@MattyBalaam I did some research before I did the manual exports again, but I could not find anything myself. It is possible that there is something buried somewhere but this was the fastest way I could do it right now.

**Comment by MattyBalaam** [comment] 2017-06-08 07:31
It looks like SVGO might get this option soon. https://github.com/svg/svgo/pull/592

**Comment by kgram** [comment] 2017-09-20 10:20
I believe the issue arises when the src attribute is longer than 4096 chars. Here is an example fiddle: https://jsfiddle.net/kgram/6cLd7c7e/4/

I think it could be fixed by checking the length of the finished data-uri and bailing to file-loader if it's too long. Could maybe be coupled with checking for the presence of a style-tag to avoid unnecessarily bailing.

**Comment by MattyBalaam** [comment] 2017-09-20 12:18
@kgram I can confirm this is the case, as reported above the 4026 threshold seemed to avoid any cases of uncoloured SVGs

**Comment by bhovhannes** [comment] 2017-09-25 07:32
As #125 has been merged I am closing this one

**Closed by bhovhannes** 2017-09-25 07:32 UTC
