### ISSUE TITLE
CSS is generated with "module.exports" JavaScript code

### ISSUE THREAD

**Issue by gajus** [bhovhannes/svg-url-loader#28] opened 2016-09-07 13:39 UTC
My loader configuration:

``` js
loaders: [
  {
    test: /\.svg/,
    loader: 'svg-url'
  },
  {
    include: path.resolve(__dirname, './../client'),
    loader: 'babel',
    test: /\.js$/,
  },
  {
    loaders: [
      {
        loader: 'style',
        query: {
          sourceMap: 1
        }
      },
      {
        loader: 'css',
        query: {
          'modules': 1,
          'importLoaders': 1,
          'localIdentName': '[path]___[name]___[local]'
        }
      },
      'resolve-url',
      'sass'
    ],
    test: /\.css$/
  },
  {
    loader: 'file?name=[name].[ext]',
    test: /\.(ttf|otf|eot|svg|woff2?)(\?[a-z0-9]+)?$/
  }
]
```

The input:

``` css
.share-facebook {
  background-image: url('./facebook.svg');
}

.share-twitter {
  background-image: url('./twitter.svg');
}
```

The output:

``` css
.client-components-ArticleComponent-static-___styles___article .client-components-ArticleComponent-static-___styles___share-controls .client-components-ArticleComponent-static-___styles___share-facebook {
  background-image: url("data:image/svg+xml;charset=utf8,module.exports = __webpack_public_path__ + 'facebook.svg';");
}

.client-components-ArticleComponent-static-___styles___article .client-components-ArticleComponent-static-___styles___share-controls .client-components-ArticleComponent-static-___styles___share-twitter {
  background-image: url("data:image/svg+xml;charset=utf8,module.exports = __webpack_public_path__ + 'twitter.svg';");
}
```

Using:

``` json
"webpack": "^2.1.0-beta.20",
"svg-url-loader": "^1.1.0",
```

**Comment by gabrielrtakeda** [comment] 2016-09-21 20:33
Same here.

**Comment by gabrielrtakeda** [comment] 2016-09-22 17:12
I'll open a PR to fix this but, i don't know if the solution i take is the best but, solved my problem.

**Comment by Geeza** [comment] 2016-09-28 21:32
Same issue here versions used match @gabrielrtakeda

**Comment by bhovhannes** [comment] 2016-09-29 14:16
Provided PR fails existing tests, so I think this issue needs more investigation.
Can you please come back with entry file (truncated to the minimum amount of lines required to reproduce the issue) and full webpack config?

**Comment by gajus** [comment] 2016-10-17 11:12
> Can you please come back with entry file (truncated to the minimum amount of lines required to reproduce the issue) and full webpack config?

Its provided in the original issue.

**Comment by bhovhannes** [comment] 2016-10-17 11:38
@gajus, do you use css file as a webpack entry?

**Comment by bentsai** [comment] 2016-10-28 15:31
I experienced the same issue and resolved it by excluding the path for my `svg` icons. A snippet of my loaders looks like this:

```
    {
      test: /\.svg$/i,
      loader: "svg-url-loader",
    },
    {
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: "file-loader",
      exclude: [path.resolve(__dirname, "src/img")],
    },
  ]
```

My situation is that I have a folder of svg icons I wanted to load as data URL's, so I could explicitly exclude these from the file loader. Maybe that can provide some additional insight, even if that's not what is going on here...

**Comment by bhovhannes** [comment] 2016-11-15 09:15
Actually, @bentsai already provided a solution. If you use file-loader, it works together with svg-url-loader, resulting in `module.exports=` in output bundle.

To avoid all issues, one should exclude svg icons referenced from CSS file from file-loader.

To be 100% sure, I've written 2 test cases, one with file-loader configured to handle both TTF and SVG files, and another one configured to handle only TTF files. 
First one failed, because of `module.exports=` in the code. 
Second one produced correct bundle.

I am closing this issue, as it is caused by wrong webpack configuration and not by bug in svg-url-loader.

**Closed by bhovhannes** 2016-11-15 09:15 UTC
